# Generated by Django 5.1.15 on 2026-09-04 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('IN_APP', 'In-app'), ('EMAIL', 'Email')], max_length=16, verbose_name='canal')),
                ('title', models.CharField(max_length=255, verbose_name='titre')),
                ('body', models.TextField(blank=True, verbose_name='contenu')),
                ('link', models.CharField(blank=True, max_length=500, verbose_name='lien')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='envoyée le')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='alerts.alert')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
