# Generated by Django 5.2.17 on 2026-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='dernière tentative'),
        ),
        migrations.AddField(
            model_name='notification',
            name='last_error',
            field=models.CharField(blank=True, max_length=500, verbose_name='dernière erreur'),
        ),
        migrations.AddField(
            model_name='notification',
            name='send_attempts',
            field=models.PositiveSmallIntegerField(default=0, verbose_name="tentatives d'envoi"),
        ),
    ]
