# Generated by Django 5.2.17 on 2026-09-22 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerts", "0003_seed_decision_rule"),
        ("amm", "0004_workflow_amm_statuts"),
        ("notifications", "0002_resilience_tracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="amm",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reminders",
                to="amm.marketingauthorization",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="reminder_date",
            field=models.DateField(blank=True, null=True, verbose_name="rappel du"),
        ),
        migrations.AddConstraint(
            model_name="notification",
            constraint=models.UniqueConstraint(
                condition=models.Q(("reminder_date__isnull", False)),
                fields=("user", "amm", "channel", "reminder_date"),
                name="notification_one_reminder_per_day",
            ),
        ),
    ]
