# Generated by Django 5.1.15 on 2026-09-04 16:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amm', '0001_initial'),
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('offset_days', models.IntegerField(default=180, verbose_name='délai avant échéance (jours)')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='WARNING', max_length=16, verbose_name='sévérité')),
                ('roles', models.JSONField(default=list, verbose_name='rôles destinataires')),
                ('channels', models.JSONField(default=list, verbose_name='canaux')),
                ('only_if_not_filed', models.BooleanField(default=True, verbose_name='seulement si aucun dépôt')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='catalog.country', verbose_name='pays (vide = globale)')),
            ],
            options={
                'verbose_name': "règle d'alerte",
                'verbose_name_plural': "règles d'alerte",
                'ordering': ['-offset_days', 'code'],
                'unique_together': {('code', 'country')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalAlert',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('due_date', models.DateField(verbose_name='échéance')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('ACKNOWLEDGED', 'Acquittée'), ('RESOLVED', 'Résolue')], db_index=True, default='OPEN', max_length=16, verbose_name='statut')),
                ('triggered_at', models.DateTimeField(blank=True, editable=False, verbose_name='déclenchée le')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acquittée le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolue le')),
                ('resolution', models.CharField(blank=True, choices=[('AUTO_FILED', 'Dépôt enregistré'), ('AUTO_RENEWED', 'Renouvellement obtenu'), ('MANUAL', 'Résolution manuelle')], max_length=16, null=True, verbose_name='résolution')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('amm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='amm.marketingauthorization')),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='assignée à')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('rule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': 'historical alerte',
                'verbose_name_plural': 'historical alertes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAlertRule',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('code', models.CharField(max_length=32, verbose_name='code')),
                ('offset_days', models.IntegerField(default=180, verbose_name='délai avant échéance (jours)')),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='WARNING', max_length=16, verbose_name='sévérité')),
                ('roles', models.JSONField(default=list, verbose_name='rôles destinataires')),
                ('channels', models.JSONField(default=list, verbose_name='canaux')),
                ('only_if_not_filed', models.BooleanField(default=True, verbose_name='seulement si aucun dépôt')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.country', verbose_name='pays (vide = globale)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "historical règle d'alerte",
                'verbose_name_plural': "historical règles d'alerte",
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_date', models.DateField(verbose_name='échéance')),
                ('status', models.CharField(choices=[('OPEN', 'Ouverte'), ('ACKNOWLEDGED', 'Acquittée'), ('RESOLVED', 'Résolue')], db_index=True, default='OPEN', max_length=16, verbose_name='statut')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='déclenchée le')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='acquittée le')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='résolue le')),
                ('resolution', models.CharField(blank=True, choices=[('AUTO_FILED', 'Dépôt enregistré'), ('AUTO_RENEWED', 'Renouvellement obtenu'), ('MANUAL', 'Résolution manuelle')], max_length=16, null=True, verbose_name='résolution')),
                ('comment', models.TextField(blank=True, verbose_name='commentaire')),
                ('amm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='amm.marketingauthorization')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL, verbose_name='assignée à')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': 'alerte',
                'verbose_name_plural': 'alertes',
                'ordering': ['due_date', '-triggered_at'],
                'unique_together': {('amm', 'rule', 'due_date')},
            },
        ),
    ]
