# Generated by Django 5.2.17 on 2026-09-28 15:02

import apps.deposits.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amm", "0004_workflow_amm_statuts"),
        ("catalog", "0003_remove_country_filing_lead_months"),
        ("documents", "0002_document_sha256_unique_active"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DepositDossier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "samples_required",
                    models.BooleanField(
                        default=True, verbose_name="échantillons demandés"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="envoyé au pays le"
                    ),
                ),
                (
                    "send_note",
                    models.TextField(blank=True, verbose_name="message d'envoi"),
                ),
                (
                    "deposited_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="attestation reçue le"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attestation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="documents.document",
                        verbose_name="attestation de dépôt",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deposited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "renewal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit",
                        to="amm.renewal",
                        verbose_name="renouvellement",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "dossier de dépôt",
                "verbose_name_plural": "dossiers de dépôt",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("CREE", "Dossier ouvert"),
                            ("PIECE", "Pièce ajoutée"),
                            ("PIECE_RETIREE", "Pièce retirée"),
                            ("ECHANTILLON", "Échantillon noté"),
                            ("ENVOI", "Envoyé au pays"),
                            ("TELECHARGEMENT", "Dossier téléchargé"),
                            ("DEPOT", "Déposé à l'agence"),
                            ("SUIVI", "Suivi à l'agence"),
                            ("DECISION", "Décision"),
                            ("ABANDON", "Abandon"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="détail")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="deposits.depositdossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "activité",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("COMMISSION", "Passage en commission"),
                            ("NOTIFICATION", "Notification de l'agence"),
                            ("COMPLEMENT", "Demande de complément"),
                            ("AUTRE", "Autre"),
                        ],
                        max_length=16,
                        verbose_name="type",
                    ),
                ),
                ("date", models.DateField(verbose_name="date")),
                ("note", models.TextField(blank=True, verbose_name="détail")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=apps.deposits.models.event_upload_to,
                        verbose_name="pièce",
                    ),
                ),
                (
                    "filename",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="nom du fichier"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="deposits.depositdossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "suivi à l'agence",
                "ordering": ["date", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("body", models.TextField(verbose_name="message")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="deposits.depositdossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "message",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="DepositSample",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(max_length=100, verbose_name="n° de lot"),
                ),
                (
                    "manufactured_on",
                    models.DateField(verbose_name="date de fabrication"),
                ),
                ("expires_on", models.DateField(verbose_name="date de péremption")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="quantité"
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="remarque"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="deposits.depositdossier",
                    ),
                ),
            ],
            options={
                "verbose_name": "échantillon",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="PieceType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=200, verbose_name="pièce")),
                (
                    "help_text",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="précision"
                    ),
                ),
                (
                    "required",
                    models.BooleanField(default=True, verbose_name="obligatoire"),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="ordre"),
                ),
                ("active", models.BooleanField(default=True, verbose_name="active")),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_pieces",
                        to="catalog.country",
                        verbose_name="pays (pièce propre au pays)",
                    ),
                ),
                (
                    "excluded_countries",
                    models.ManyToManyField(
                        blank=True,
                        related_name="deposit_pieces_excluded",
                        to="catalog.country",
                        verbose_name="pays qui ne la demandent pas",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce du dossier de dépôt",
                "verbose_name_plural": "pièces du dossier de dépôt",
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="DepositPiece",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="libellé"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=apps.deposits.models.piece_upload_to,
                        verbose_name="fichier",
                    ),
                ),
                (
                    "filename",
                    models.CharField(max_length=255, verbose_name="nom du fichier"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="type MIME"
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(default=0, verbose_name="taille"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dossier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="deposits.depositdossier",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "piece_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="deposits.piecetype",
                        verbose_name="pièce (vide : autre pièce)",
                    ),
                ),
            ],
            options={
                "verbose_name": "pièce jointe au dossier",
                "ordering": ["uploaded_at"],
            },
        ),
    ]
