# Generated by Django 5.1.15 on 2026-09-04 16:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='code ISO')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('authority', models.CharField(blank=True, max_length=200, verbose_name='autorité réglementaire')),
                ('validity_years', models.PositiveSmallIntegerField(default=5, verbose_name='durée de validité (années)')),
                ('filing_lead_months', models.PositiveSmallIntegerField(default=6, verbose_name='délai de dépôt (mois)')),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=64, verbose_name='fuseau horaire')),
            ],
            options={
                'verbose_name': 'pays',
                'verbose_name_plural': 'pays',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='libellé normalisé')),
                ('dci', models.CharField(blank=True, max_length=255, verbose_name='DCI')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='dosage')),
                ('form', models.CharField(blank=True, max_length=100, verbose_name='forme')),
                ('presentation', models.CharField(blank=True, max_length=100, verbose_name='présentation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
            ],
            options={
                'verbose_name': 'produit',
                'verbose_name_plural': 'produits',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductRange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(choices=[('GENERALE', 'Générale'), ('CARDIO', 'Cardio'), ('BIEN_ETRE', 'Bien-être')], max_length=16, unique=True, verbose_name='code')),
                ('label', models.CharField(max_length=100, verbose_name='libellé')),
            ],
            options={
                'verbose_name': 'gamme',
                'verbose_name_plural': 'gammes',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCountry',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('iso2', models.CharField(db_index=True, max_length=2, verbose_name='code ISO')),
                ('name', models.CharField(max_length=100, verbose_name='nom')),
                ('authority', models.CharField(blank=True, max_length=200, verbose_name='autorité réglementaire')),
                ('validity_years', models.PositiveSmallIntegerField(default=5, verbose_name='durée de validité (années)')),
                ('filing_lead_months', models.PositiveSmallIntegerField(default=6, verbose_name='délai de dépôt (mois)')),
                ('timezone', models.CharField(default='Africa/Dakar', max_length=64, verbose_name='fuseau horaire')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical pays',
                'verbose_name_plural': 'historical pays',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_name', models.CharField(max_length=255, unique=True, verbose_name='libellé source')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='catalog.product')),
            ],
            options={
                'verbose_name': 'alias produit',
                'verbose_name_plural': 'alias produits',
                'ordering': ['raw_name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='range',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productrange', verbose_name='gamme'),
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='libellé normalisé')),
                ('dci', models.CharField(blank=True, max_length=255, verbose_name='DCI')),
                ('dosage', models.CharField(blank=True, max_length=100, verbose_name='dosage')),
                ('form', models.CharField(blank=True, max_length=100, verbose_name='forme')),
                ('presentation', models.CharField(blank=True, max_length=100, verbose_name='présentation')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('range', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.productrange', verbose_name='gamme')),
            ],
            options={
                'verbose_name': 'historical produit',
                'verbose_name_plural': 'historical produits',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
