# Generated by Django 5.2.17 on 2026-09-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_product_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="country",
            name="filing_lead_months",
        ),
        migrations.RemoveField(
            model_name="historicalcountry",
            name="filing_lead_months",
        ),
    ]
