# Generated by Django 5.1.15 on 2026-09-04 16:06

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalMarketingAuthorization',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('original_number', models.CharField(blank=True, max_length=100, verbose_name="n° AMM d'origine")),
                ('original_start_date', models.DateField(blank=True, null=True, verbose_name="date de début d'origine")),
                ('original_end_date', models.DateField(blank=True, null=True, verbose_name="date de fin d'origine")),
                ('original_end_date_manual', models.BooleanField(default=False, verbose_name='date de fin saisie manuellement')),
                ('status', models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expirée'), ('IN_PROCESS', "En cours d'instruction"), ('INDETERMINE', 'Indéterminé')], db_index=True, default='INDETERMINE', max_length=16, verbose_name='statut')),
                ('urgency', models.CharField(choices=[('OK', 'OK'), ('A_PLANIFIER', 'À planifier'), ('DEPOT_URGENT', 'Dépôt urgent'), ('CRITIQUE', 'Critique'), ('EXPIRE', 'Expirée'), ('EN_INSTRUCTION', 'En instruction')], db_index=True, default='A_PLANIFIER', max_length=16, verbose_name='urgence')),
                ('effective_end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='date de fin effective')),
                ('filing_deadline', models.DateField(blank=True, null=True, verbose_name='deadline de dépôt')),
                ('dossier_state', models.CharField(choices=[('COMPLET', 'Dossier complet'), ('INCOMPLET', 'Dossier incomplet'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=16, verbose_name='état du dossier')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('country', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.country', verbose_name='pays')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'historical AMM',
                'verbose_name_plural': 'historical AMM',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='MarketingAuthorization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_number', models.CharField(blank=True, max_length=100, verbose_name="n° AMM d'origine")),
                ('original_start_date', models.DateField(blank=True, null=True, verbose_name="date de début d'origine")),
                ('original_end_date', models.DateField(blank=True, null=True, verbose_name="date de fin d'origine")),
                ('original_end_date_manual', models.BooleanField(default=False, verbose_name='date de fin saisie manuellement')),
                ('status', models.CharField(choices=[('VALIDE', 'Valide'), ('EXPIRE', 'Expirée'), ('IN_PROCESS', "En cours d'instruction"), ('INDETERMINE', 'Indéterminé')], db_index=True, default='INDETERMINE', max_length=16, verbose_name='statut')),
                ('urgency', models.CharField(choices=[('OK', 'OK'), ('A_PLANIFIER', 'À planifier'), ('DEPOT_URGENT', 'Dépôt urgent'), ('CRITIQUE', 'Critique'), ('EXPIRE', 'Expirée'), ('EN_INSTRUCTION', 'En instruction')], db_index=True, default='A_PLANIFIER', max_length=16, verbose_name='urgence')),
                ('effective_end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='date de fin effective')),
                ('filing_deadline', models.DateField(blank=True, null=True, verbose_name='deadline de dépôt')),
                ('dossier_state', models.CharField(choices=[('COMPLET', 'Dossier complet'), ('INCOMPLET', 'Dossier incomplet'), ('INCONNU', 'Inconnu')], default='INCONNU', max_length=16, verbose_name='état du dossier')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amms', to='catalog.country', verbose_name='pays')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_amms', to=settings.AUTH_USER_MODEL, verbose_name='responsable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='amms', to='catalog.product', verbose_name='produit')),
            ],
            options={
                'verbose_name': 'AMM',
                'verbose_name_plural': 'AMM',
                'ordering': ['country__iso2', 'product__name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRenewal',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('sequence', models.PositiveIntegerField(editable=False, verbose_name="n° d'ordre")),
                ('workflow_status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_PREPARATION', 'En préparation'), ('DEPOSE', 'Déposé'), ('EN_INSTRUCTION', 'En instruction'), ('OBTENU', 'Obtenu'), ('REJETE', 'Rejeté'), ('ABANDONNE', 'Abandonné')], default='PLANIFIE', max_length=16, verbose_name='statut du workflow')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='date de dépôt')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='date de décision')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='n° AMM')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('end_date_manual', models.BooleanField(default=False, verbose_name='date de fin saisie manuellement')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('amm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='amm.marketingauthorization', verbose_name='AMM')),
            ],
            options={
                'verbose_name': 'historical renouvellement',
                'verbose_name_plural': 'historical renouvellements',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Renewal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField(editable=False, verbose_name="n° d'ordre")),
                ('workflow_status', models.CharField(choices=[('PLANIFIE', 'Planifié'), ('EN_PREPARATION', 'En préparation'), ('DEPOSE', 'Déposé'), ('EN_INSTRUCTION', 'En instruction'), ('OBTENU', 'Obtenu'), ('REJETE', 'Rejeté'), ('ABANDONNE', 'Abandonné')], default='PLANIFIE', max_length=16, verbose_name='statut du workflow')),
                ('filing_date', models.DateField(blank=True, null=True, verbose_name='date de dépôt')),
                ('decision_date', models.DateField(blank=True, null=True, verbose_name='date de décision')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='n° AMM')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='date de fin')),
                ('end_date_manual', models.BooleanField(default=False, verbose_name='date de fin saisie manuellement')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='amm.marketingauthorization', verbose_name='AMM')),
            ],
            options={
                'verbose_name': 'renouvellement',
                'verbose_name_plural': 'renouvellements',
                'ordering': ['amm', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='marketingauthorization',
            index=models.Index(fields=['country', 'status'], name='amm_country_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='marketingauthorization',
            unique_together={('product', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='renewal',
            unique_together={('amm', 'sequence')},
        ),
    ]
