# Generated by Django 5.2.17 on 2026-09-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmarketingauthorization',
            name='holder',
            field=models.CharField(blank=True, max_length=255, verbose_name='titulaire / laboratoire'),
        ),
        migrations.AddField(
            model_name='marketingauthorization',
            name='holder',
            field=models.CharField(blank=True, max_length=255, verbose_name='titulaire / laboratoire'),
        ),
    ]
