# Generated by Django 5.1.15 on 2026-09-04 16:06

import apps.documents.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('AMM', 'AMM'), ('RECEPISSE', 'Récépissé de dépôt'), ('COURRIER', "Courrier de l'autorité"), ('AUTRE', 'Autre')], default='AMM', max_length=16, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titre')),
                ('document_date', models.DateField(db_index=True, verbose_name='date du document')),
                ('file', models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_to, verbose_name='fichier')),
                ('content_type', models.CharField(default='application/pdf', max_length=64, verbose_name='type MIME')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='taille (octets)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de pages')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_current', models.BooleanField(default=True, verbose_name='version courante')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='téléversé le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('amm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='amm.marketingauthorization', verbose_name='AMM')),
                ('renewal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='amm.renewal', verbose_name='renouvellement')),
                ('replaces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.document', verbose_name='remplace')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='téléversé par')),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-document_date', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocument',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('kind', models.CharField(choices=[('AMM', 'AMM'), ('RECEPISSE', 'Récépissé de dépôt'), ('COURRIER', "Courrier de l'autorité"), ('AUTRE', 'Autre')], default='AMM', max_length=16, verbose_name='type')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='titre')),
                ('document_date', models.DateField(db_index=True, verbose_name='date du document')),
                ('file', models.TextField(max_length=500, verbose_name='fichier')),
                ('content_type', models.CharField(default='application/pdf', max_length=64, verbose_name='type MIME')),
                ('sha256', models.CharField(db_index=True, max_length=64, verbose_name='empreinte SHA-256')),
                ('size_bytes', models.PositiveBigIntegerField(default=0, verbose_name='taille (octets)')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='nombre de pages')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('is_current', models.BooleanField(default=True, verbose_name='version courante')),
                ('uploaded_at', models.DateTimeField(blank=True, db_index=True, editable=False, verbose_name='téléversé le')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('amm', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='amm.marketingauthorization', verbose_name='AMM')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('renewal', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='amm.renewal', verbose_name='renouvellement')),
                ('replaces', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document', verbose_name='remplace')),
                ('uploaded_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='téléversé par')),
            ],
            options={
                'verbose_name': 'historical document',
                'verbose_name_plural': 'historical documents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['amm', '-document_date', '-uploaded_at'], name='doc_amm_chrono_idx'),
        ),
    ]
