# Generated by Django 5.2.17 on 2026-09-27 21:52

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("amm", "0004_workflow_amm_statuts"),
        ("catalog", "0003_remove_country_filing_lead_months"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinderCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("CORRIGE", "Corrigé"),
                            ("ABSENT", "Absent du classeur"),
                        ],
                        max_length=16,
                        verbose_name="constat",
                    ),
                ),
                (
                    "corrections",
                    models.JSONField(
                        blank=True, default=list, verbose_name="corrections"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("checked_at", models.DateTimeField(verbose_name="vérifié le")),
                (
                    "amm",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="binder_check",
                        to="amm.marketingauthorization",
                        verbose_name="AMM",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vérifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "vérification de classeur",
                "verbose_name_plural": "vérifications de classeur",
            },
        ),
        migrations.CreateModel(
            name="BinderExtraPage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "binder_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="classeur"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, verbose_name="produit lu sur le dossier"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="signalé le"),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.country",
                        verbose_name="pays",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="signalé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "page en trop",
                "verbose_name_plural": "pages en trop",
                "ordering": ["product_name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBinderCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("CONFORME", "Conforme"),
                            ("CORRIGE", "Corrigé"),
                            ("ABSENT", "Absent du classeur"),
                        ],
                        max_length=16,
                        verbose_name="constat",
                    ),
                ),
                (
                    "corrections",
                    models.JSONField(
                        blank=True, default=list, verbose_name="corrections"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="note")),
                ("checked_at", models.DateTimeField(verbose_name="vérifié le")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "amm",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="amm.marketingauthorization",
                        verbose_name="AMM",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="vérifié par",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical vérification de classeur",
                "verbose_name_plural": "historical vérifications de classeur",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
