# Generated by Django 5.2.17 on 2026-09-27 22:47

import apps.binders.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binders", "0001_initial"),
        ("catalog", "0003_remove_country_filing_lead_months"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinderExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "binder_key",
                    models.CharField(
                        db_index=True, max_length=40, verbose_name="classeur"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("RUNNING", "En préparation"),
                            ("READY", "Prêt"),
                            ("FAILED", "Échec"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="statut",
                    ),
                ),
                (
                    "progress_done",
                    models.PositiveIntegerField(default=0, verbose_name="AMM traitées"),
                ),
                (
                    "progress_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="AMM à traiter"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        max_length=300,
                        upload_to=apps.binders.models.export_upload_to,
                        verbose_name="fichier",
                    ),
                ),
                (
                    "size_bytes",
                    models.PositiveBigIntegerField(
                        default=0, verbose_name="taille (octets)"
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(default=0, verbose_name="pages"),
                ),
                (
                    "decisions",
                    models.PositiveIntegerField(
                        default=0, verbose_name="décisions jointes"
                    ),
                ),
                (
                    "unavailable",
                    models.PositiveIntegerField(
                        default=0,
                        verbose_name="scans illisibles ou absents du stockage",
                    ),
                ),
                (
                    "without_scan",
                    models.PositiveIntegerField(
                        default=0, verbose_name="AMM sans scan"
                    ),
                ),
                ("error", models.TextField(blank=True, verbose_name="erreur")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="demandé le"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="commencé le"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="terminé le"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.country",
                        verbose_name="pays",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="demandé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "export de classeur",
                "verbose_name_plural": "exports de classeur",
                "ordering": ["-created_at"],
            },
        ),
    ]
