# Generated by Django 5.2.17 on 2026-09-27 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("binders", "0002_export_avec_decisions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BinderPresence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "binder_key",
                    models.CharField(max_length=40, verbose_name="classeur"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(db_index=True, verbose_name="vu le"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "classeur ouvert",
                "verbose_name_plural": "classeurs ouverts",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("binder_key", "user"), name="binder_presence_uniq"
                    )
                ],
            },
        ),
    ]
