# Generated by Django 5.2.17 on 2026-09-28 12:24

from django.db import migrations, models


def snapshot_existing_checks(apps, schema_editor):
    """Constats déjà faits : les valeurs actuelles deviennent les valeurs vérifiées."""
    BinderCheck = apps.get_model("binders", "BinderCheck")
    Renewal = apps.get_model("amm", "Renewal")

    def iso(value):
        return value.isoformat() if value else None

    for check in BinderCheck.objects.select_related("amm"):
        amm = check.amm
        snapshot = {
            "original": {
                "number": amm.original_number,
                "start_date": iso(amm.original_start_date),
                "end_date": iso(amm.original_end_date),
            }
        }
        renewal = (
            Renewal.objects.filter(amm=amm, workflow_status="OBTENU").order_by("-sequence").first()
        )
        if renewal is not None:
            snapshot["renewal"] = {
                "number": renewal.number,
                "start_date": iso(renewal.start_date),
                "end_date": iso(renewal.end_date),
            }
        check.snapshot = snapshot
        check.save(update_fields=["snapshot"])


class Migration(migrations.Migration):

    dependencies = [
        ("binders", "0003_classeurs_ouverts"),
    ]

    operations = [
        migrations.AddField(
            model_name="bindercheck",
            name="snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="valeurs vérifiées"
            ),
        ),
        migrations.AddField(
            model_name="historicalbindercheck",
            name="snapshot",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="valeurs vérifiées"
            ),
        ),
        migrations.RunPython(snapshot_existing_checks, migrations.RunPython.noop),
    ]
