# Generated by Django 5.1.15 on 2026-09-04 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('amm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to='imports/%Y/%m/', verbose_name='classeur')),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'En cours'), ('DONE', 'Terminé'), ('FAILED', 'Échoué')], default='PENDING', max_length=16, verbose_name='statut')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='résumé')),
                ('reference_date', models.DateField(blank=True, null=True, verbose_name='date de référence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'import',
                'verbose_name_plural': 'imports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportRow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sheet', models.CharField(max_length=100, verbose_name='onglet')),
                ('row_number', models.PositiveIntegerField(verbose_name='ligne')),
                ('raw', models.JSONField(default=dict, verbose_name='données brutes')),
                ('outcome', models.CharField(choices=[('CREATED', 'Créée'), ('UPDATED', 'Mise à jour'), ('SKIPPED', 'Inchangée'), ('ERROR', 'Erreur'), ('WARNING', 'Avertissement')], max_length=16, verbose_name='résultat')),
                ('message', models.TextField(blank=True, verbose_name='message')),
                ('amm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='amm.marketingauthorization')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='imports.importbatch')),
            ],
            options={
                'verbose_name': "ligne d'import",
                'verbose_name_plural': "lignes d'import",
                'ordering': ['sheet', 'row_number'],
            },
        ),
    ]
