# Generated by Django 5.2.17 on 2026-09-10 09:44

import apps.imports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amm', '0002_historicalmarketingauthorization_holder_and_more'),
        ('catalog', '0002_product_key'),
        ('documents', '0002_document_sha256_unique_active'),
        ('imports', '0002_importbatch_dry_run'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('root_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('RUNNING', 'Analyse en cours'), ('READY', 'À valider'), ('APPLIED', 'Enregistré'), ('FAILED', 'Analyse échouée')], default='PENDING', max_length=16)),
                ('preview', models.JSONField(blank=True, default=dict)),
                ('preview_token', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('amm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossier_imports', to='amm.marketingauthorization')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DossierFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('relative_path', models.CharField(max_length=500)),
                ('file', models.FileField(max_length=500, upload_to=apps.imports.models.dossier_upload_to)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('content_type', models.CharField(max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('extraction', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dossier_sources', to='documents.document')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='imports.dossierimport')),
            ],
            options={
                'ordering': ['relative_path'],
            },
        ),
        migrations.CreateModel(
            name='DossierChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field', models.CharField(max_length=100)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('confidence', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='DOSSIER_IMPORT', editable=False, max_length=32)),
                ('reason', models.CharField(default='Correction à partir du dossier réglementaire importé', max_length=255)),
                ('amm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentary_changes', to='amm.marketingauthorization')),
                ('renewal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='amm.renewal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('proof_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='imports.dossierfile')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit', to='imports.dossierimport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='dossierfile',
            constraint=models.UniqueConstraint(fields=('batch', 'relative_path'), name='dossier_path_unique'),
        ),
        migrations.AddConstraint(
            model_name='dossierchange',
            constraint=models.CheckConstraint(condition=models.Q(('confidence__gte', 0), ('confidence__lte', 100)), name='dossier_change_confidence_range'),
        ),
    ]
