# Generated by Django 5.2.17 on 2026-09-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imports', '0003_dossierimport_dossierfile_dossierchange_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossierimport',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
