# Generated by Django 5.2.17 on 2026-09-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0005_dossierimport_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierimport",
            name="auto_applied",
            field=models.BooleanField(default=False),
        ),
    ]
