# Generated by Django 5.2.17 on 2026-09-23 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("amm", "0004_workflow_amm_statuts"),
        ("imports", "0006_dossierimport_auto_applied"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="dossierimport",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("RUNNING", "Analyse en cours"),
                    ("READY", "Prêt à ranger"),
                    ("QUESTION", "Question : quelle AMM ?"),
                    ("APPLIED", "Rangé"),
                    ("FAILED", "Analyse échouée"),
                ],
                default="PENDING",
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="DossierReviewPoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("field", models.CharField(blank=True, max_length=100)),
                ("recorded_value", models.JSONField(blank=True, null=True)),
                ("scan_value", models.JSONField(blank=True, null=True)),
                ("confidence", models.PositiveSmallIntegerField(default=0)),
                ("message", models.TextField()),
                ("fingerprint", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "À vérifier"),
                            ("APPLIED", "Valeur du scan appliquée"),
                            ("IGNORED", "Ignoré"),
                        ],
                        default="OPEN",
                        max_length=16,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "amm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_points",
                        to="amm.marketingauthorization",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_points",
                        to="imports.dossierimport",
                    ),
                ),
                (
                    "proof_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="imports.dossierfile",
                    ),
                ),
                (
                    "renewal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="amm.renewal",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["amm", "status"], name="review_point_amm_status"
                    )
                ],
            },
        ),
    ]
