# Generated by Django 5.2.17 on 2026-09-25 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0007_dossier_review_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="dossierimport",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
