# Generated by Django 5.2.17 on 2026-09-28 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("imports", "0009_documents_communs_hors_sujet"),
    ]

    operations = [
        migrations.AddField(
            model_name="importbatch",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="démarré le"
            ),
        ),
    ]
